### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/mmimport/export/users.json'

### ISSUE THREAD

**Issue by flaakesk8** [ergon/migratemost#11]
HI, I'm running this command with a very small extracted export of our Hipchat server (on-prem) Atlassian HipChat 2.4.3 (2018.10.08.214558)

./migratemost.py -t MMtest -o /home/mmimport/export -i /home/mmimport/export -v --migrate-all

thats the full output of the command

2019-08-29 09:59:52,735 - INFO - Starting migration
2019-08-29 09:59:52,735 - INFO - Team migration started
2019-08-29 09:59:52,736 - INFO - Team migration finished
2019-08-29 09:59:52,736 - INFO - User migration started
Traceback (most recent call last):
  File "./migratemost.py", line 1277, in <module>
    main()
  File "./migratemost.py", line 1114, in main
    mm_users = migrate_users()
  File "./migratemost.py", line 577, in migrate_users
    hc_users = load_hipchat_users()
  File "./migratemost.py", line 504, in load_hipchat_users
    with open('%s/users.json' % migration_input_path, 'r') as hc_users_file:
IOError: [Errno 2] No such file or directory: '/home/mmimport/export/users.json'

also when I check the output directory I only see one file mm_team.jsonl

can you please tell me what's the issue here? I'm running everything as root user, so I guess permissions are not the problem

**Comment by flaakesk8** [comment]
please close the issue I should learn to read input and output had twice -o /home/mmimport/export -i /home/mmimport/export 

sorry
