### ISSUE TITLE
Channel migration crashes with "TypeError: unhashable type: 'dict'"

### ISSUE THREAD

**Issue by jby** [ergon/migratemost#2]
2019-04-30 09:16:40,859 - INFO - Channel migration started
Traceback (most recent call last):
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 1213, in <module>
    main()
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 1075, in main
    mm_channels = migrate_channels()
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 653, in migrate_channels
    mm_channel = Channel.from_hc_room(name, display_name, header, hc_room)
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 243, in from_hc_room
    mm_channel._members = set(hc_room['members'])
TypeError: unhashable type: 'dict'

**Comment by 7-plus-t** [comment]
This was caused by the field `member` in the object `room` being a dictionary in Hipchat Server export, not a list of integers as it is in Hipchat DataCenter export. I've changed the script to handle both variants.
